// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljczkvavawrrmdvwkkfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqY3prdmF2YXdycm1kdndra2ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTM4MTIsImV4cCI6MjA2NjY2OTgxMn0.F83YQadSIlkwicIHExL-e4DPWSpK_6hq4kHMi20_yYs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);